pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - master

parameters:
- name: package
  type: string
  displayName: 'Select package to publish'
  default: 'usf-parity'
  values:
  - usf-http
  - usf-parity
  - usf-redis
  - usf-middleware
  - usf-mssql
  - usf-mysql
  - usf-oracle
  - usf-common
  - usf-cron

variables: 
  NODE_VERSION: '24.x'
steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: ${{ variables.NODE_VERSION }}
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: $(System.DefaultWorkingDirectory)/${{ parameters.package }}/.npmrc
  displayName: 'Authenticate with npm registry'

- script: |
    cd $(System.DefaultWorkingDirectory)/${{ parameters.package }}
    npm install
  displayName: 'Install dependencies'

- script: |
    set -e
    cd $(System.DefaultWorkingDirectory)/${{ parameters.package }}

    LOCAL_VERSION=$(npm pkg get version | tr -d '"')
    echo "Local version: $LOCAL_VERSION"

    ADO_VERSION=$(npm view ${{ parameters.package }} version || echo "0.0.0")
    echo "Version in npm registry: $ADO_VERSION"
    if [ "$LOCAL_VERSION" = "$ADO_VERSION" ]; then
      echo "Version $LOCAL_VERSION already exists in npm registry. Skipping publish."
      exit 0
    fi
    npm publish
  displayName: 'Publish package to npm'